#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# spaces
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create

yabai -m space 1 --label '1: Terminals'
yabai -m space 2 --label '2: Code'
yabai -m space 3 --label '3: Browser'
yabai -m space 4 --label '4: Messaging'
yabai -m space 5 --label '5: Media'
yabai -m space 6 --label '6: Office'
yabai -m space 7 --label '7: Extra'
yabai -m space 8 --label '8: Extra'
yabai -m space 9 --label '9: Extra'
yabai -m space 0 --label '10: Extra'

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config external_bar                 all:20:0
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# floating apps
yabai -m rule --add app="Karabiner-Elements" manage=off
yabai -m rule --add app="System Preferences" manage=off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# Ubersicht
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-jsx\"'"

# if using multple displays, add an additional rule for "display_changed" event
yabai -m signal --add event=display_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-jsx\"'"


echo "yabai configuration loaded.."
